Release/v0.6.0
upb-uc4/lagom-core pull request #205
Opened 2020-08-17 10:31 UTC by lrschaef

### Reason for this PR
- Sprint increment of sprint 5 should be on master

### Changes in this PR

#### All Services
- Added predefined standard exceptions to CustomException
- Changed exceptions to use these standard exceptions whereever possible
- Fixed ambigous endpoints caused by UC4Service Trait

#### Course Service
- Fixed search for courseName not being fuzzy

#### Matriculation Service
- Added call to immatriculate a Student for one specific fieldOfStudy + semester
- Added call to fetch the complete matriculation history of a specific Student
- Added update call to UserService to cache the latestImmatriculation

#### User Service
- Added check in update call if the fields are editable (even for an admin)
- Added phone number field to all users
- Added latestImmatriculation to student
- Added function to update latestImmatriculation
- Removed now obsolete fields (fieldOfStudy, semesterCount, immatriculationStatus)
- Added functionality that fetching a user returns less personal info, when invoked by a non-Admin that is not the user to fetch
- Added query parameter "usernames" to getAllUsers, getAllStudents, getAllLecturers, getAllAdmins to filter with
- Splitted editableFields method into two methods, one for permission check, one for possibility check
- Fixed a bug that allowed houseNumbers to be empty
- Fixed a bug that allowed "01" and "001" as matriculationId's, while not recognising them as the same number

2020-08-19 12:02 UTC, bhermann requested changes

2020-08-19 12:09 UTC, lrschaef commented on product_code/lagom/matriculation_service/api/src/main/scala/de/upb/cs/uc4/matriculation/model/PutMessageMatriculationData.scala
> +    val fos = List("Computer Science","Philosophy","Media Sciences", "Economics", "Mathematics", "Physics", "Chemistry",
Agreed, this task is on our ZenHub board since the very beginning, since we also use that list in the UserService for the students.

2020-08-19 14:48 UTC, ldklenner commented on product_code/lagom/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
> +    val mailRegex = """(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a
If I am correct the regex is almost identical to [this](https://www.regular-expressions.info/email.html) (Section: The Official Standard: RFC 5322), which tries to capture the broad range of the [RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.4) standard. This regex seems to be rather inconvenient as it is hard to maintain and in this context it is hard to check for catastrophic backtracking. Do you have any for recommendation for debugging? There seems to be no free tool to assist with catastrophic backtracking for regexs which are not valided on the PHP regex engine.

I suspect that this is not the only validation which might take to long to complete in worst cases. Is it a valid idea to execute such computations in a future and wait for bounded time for the completion? Or this this considered unreliable and hacky?

2020-08-20 11:50 UTC, david-buderus commented on product_code/lagom/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
> +            hyperLedgerSession.read[ImmatriculationData]("getMatriculationData", student.matriculationId)
Already happend in the new hyperledger api (v0.6.1)

2020-08-31 09:07 UTC, dhelmert approved these changes

2020-08-31 09:07 UTC, david-buderus approved these changes

2020-08-31 09:10 UTC, ldklenner approved these changes

2020-09-01 07:27 UTC, bhermann commented on product_code/lagom/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/Utils.scala
> +        if (semester.substring(0, 2) == "WS" && (semester.substring(4, 6).toInt + 1 != semester.substring(7, 9).toInt)) {
Great change! I think it became much more readable. 
Just a thought: What will happen with a non-sense input such as `WSAA/BB` which fails the `toInt` conversion?

2020-09-01 07:33 UTC, bhermann commented on product_code/lagom/shared/client/src/main/scala/de/upb/cs/uc4/shared/client/Utils.scala
> +        if (semester.substring(0, 2) == "WS" && (semester.substring(4, 6).toInt + 1 != semester.substring(7, 9).toInt)) {
Ahhh reread the code... It fails the regex match then. Perfect.

2020-09-01 07:41 UTC, bhermann commented on product_code/lagom/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
> +    val mailRegex = """(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a
Two thoughts on this: 
1. Yes there seems to be no automated support on this so regex have to be inspected manually for this behavior. Weird... I hoped someone would have done something about this already. Anyone up for a PhD thesis on this? 
2. As manual inspection is NEVER as reliable as automated you'll need some safety bulkheads in place. Doing this in a `Future` is a brilliant idea. Simply wrap it and execute it with a reasonable timeout that will catch any weird backtracking going on.

2020-09-01 07:42 UTC, bhermann commented on product_code/lagom/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/User.scala
> +    val mailRegex = """(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a
Feel free to add a solution to (2) in a future version.

2020-09-01 07:42 UTC, bhermann approved these changes

2020-09-01 07:49 UTC, merged