Feature/validation timeout
upb-uc4/lagom-core pull request #309
Opened 2020-09-30 08:50 UTC by lrschaef

### Reason for this PR
- #251 

### Changes in this PR
- Closes #251 

- [X] Test written
- [ ] Changelog updated

2020-09-30 10:16 UTC, david-buderus requested changes

2020-09-30 10:16 UTC, david-buderus commented on product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
> +            case e: Exception        => throw e
This needs to be changed into a Internal Server Error
```suggestion
            case e: Exception        => throw UC4Exception.InternalServerError("Validation Error", e.getMessage)
```

2020-09-30 10:16 UTC, david-buderus commented on product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
> +            case e: Exception        => throw e
This needs to be changed into a Internal Server Error
```suggestion
            case e: Exception        => throw UC4Exception.InternalServerError("Validation Error", e.getMessage)
```

2020-09-30 10:16 UTC, david-buderus commented on product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
> +          case e: Exception        => throw e
This needs to be changed into a Internal Server Error
```suggestion
            case e: Exception        => throw UC4Exception.InternalServerError("Validation Error", e.getMessage)
```

2020-09-30 10:16 UTC, david-buderus commented on product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
> +          case e: Exception        => throw e
This needs to be changed into a Internal Server Error
```suggestion
          case e: Exception        => throw UC4Exception.InternalServerError("Validation Error", e.getMessage)
```

2020-09-30 10:16 UTC, david-buderus commented on product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
> +        case e: Exception        => throw e
This needs to be changed into a Internal Server Error
```suggestion
        case e: Exception        => throw UC4Exception.InternalServerError("Validation Error", e.getMessage)
```

2020-09-30 10:16 UTC, david-buderus commented on product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
> +              case e: Exception        => throw e
This needs to be changed into a Internal Server Error
```suggestion
              case e: Exception        => throw UC4Exception.InternalServerError("Validation Error", e.getMessage)
```

2020-10-01 10:08 UTC, ldklenner approved these changes

2020-10-02 08:08 UTC, david-buderus requested changes

2020-10-02 08:08 UTC, david-buderus commented on product_code/authentication_service/impl/src/main/scala/de/upb/cs/uc4/authentication/impl/AuthenticationServiceImpl.scala
> +            Await.result(authUser.validate, 5.seconds)
The timeout should be defined in the application.conf
And than loaded into a lazy val

2020-10-02 08:08 UTC, david-buderus commented on product_code/course_service/impl/src/main/scala/de/upb/cs/uc4/course/impl/CourseServiceImpl.scala
> +          Await.result(updatedCourse.validate, 5.seconds)
The timeout should be defined in the application.conf
And than loaded into a lazy val

2020-10-02 08:08 UTC, david-buderus commented on product_code/matriculation_service/impl/src/main/scala/de/upb/cs/uc4/matriculation/impl/MatriculationServiceImpl.scala
> +          Await.result(message.validate, 5.seconds)
The timeout should be defined in the application.conf
And than loaded into a lazy val

2020-10-02 08:08 UTC, david-buderus commented on product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
> +        Await.result(validationErrorsFuture, 5.seconds)
The timeout should be defined in the application.conf
And than loaded into a lazy val

2020-10-02 08:08 UTC, david-buderus commented on product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserServiceImpl.scala
> +              Await.result(user.validate, 5.seconds)
The timeout should be defined in the application.conf
And than loaded into a lazy val

2020-10-02 08:53 UTC, david-buderus approved these changes

2020-10-05 09:06 UTC, merged