Feature/user deletion
upb-uc4/lagom-core pull request #375
Opened 2020-11-12 10:08 UTC by dhelmert

### Reason for this PR
- Deleting a User completely breaks some logic, as a course's creator can be deleted while the course still exists. Therefore, soft-deletion

### Changes in this PR
- Replaced DELETE call with soft delete
- Added "isActive" flag to User object, which is "true" on creation, and "false" after soft-deletion
- Added Query parameter "only_active" to all "getAll" calls
- Split deletion topic into two, one for auth and one for cert service, since dependencies do not allow to send the role in a topic to auth service
- Changed the deletion topic behaviour: Upon soft deletion; the AuthUser is fully deleted and the CertUser is fully deleted (if a non-lecturer is soft-deleted). If a lecturer is deleted CertUser retains enrollmentId and certificate

- [ ] Test written
- [ ] Changelog updated

2020-11-16 10:26 UTC, dhelmert commented
We cannot manually test until examination regulations are merged, since the changes that allow local testing are on that branch.

2020-11-25 12:37 UTC, lrschaef requested changes

2020-11-25 12:37 UTC, lrschaef commented on product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
> +  def getAllStudents(usernames: Option[String], only_active: Option[Boolean]): ServiceCall[NotUsed, Seq[Student]]
The parameter only_active does not conform to our naming scheme.
As the name in the impl and stub is onlyActive, it should be changed to that.
Same for the getAllLecturers/Admins and getAllUsers methods.

2020-11-25 12:37 UTC, lrschaef commented on product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
> +        restCall(Method.GET, pathPrefix + "/users?usernames&only_active", getAllUsers _),
Remember to also change the name of the parameter here and in the other restCalls

2020-11-25 12:37 UTC, lrschaef commented on product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/model/user/Admin.scala
>    //override def toPublic: Admin = super.toPublic.asInstanceOf[Admin]
I know this is not a mistake on this branch, but this should be removed. We may do that here or after the merge directly on develop

2020-11-25 14:14 UTC, ldklenner approved these changes

2020-11-25 14:14 UTC, ldklenner commented on product_code/user_service/impl/src/main/scala/de/upb/cs/uc4/user/impl/UserSerializerRegistry.scala
> +import de.upb.cs.uc4.user.impl.events.{ OnLatestMatriculationUpdate, OnUserCreate, OnUserForceDelete, OnUserSoftDelete, OnUserUpdate }
Optimize imports to contain not more than 4 entries

```suggestion
import de.upb.cs.uc4.user.impl.events._
```

2020-11-26 08:48 UTC, lrschaef commented on product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
> +  def getAllStudents(usernames: Option[String], only_active: Option[Boolean]): ServiceCall[NotUsed, Seq[Student]]
I just got informed that this is because of the REST API. Because I do not want to change the API we leave it as it is.

2020-11-26 10:21 UTC, david-buderus requested changes

2020-11-26 10:21 UTC, david-buderus commented on product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
> +  def getAllUsers(usernames: Option[String], only_active: Option[Boolean]): ServiceCall[NotUsed, GetAllUsersResponse]
```suggestion
  def getAllUsers(usernames: Option[String], onlyActive: Option[Boolean]): ServiceCall[NotUsed, GetAllUsersResponse]
```
We are using camelCase

2020-11-26 10:21 UTC, david-buderus commented on product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
> +  def getAllStudents(usernames: Option[String], only_active: Option[Boolean]): ServiceCall[NotUsed, Seq[Student]]
```suggestion
  def getAllStudents(usernames: Option[String], onlyActive: Option[Boolean]): ServiceCall[NotUsed, Seq[Student]]
```
We are using camelCase

2020-11-26 10:21 UTC, david-buderus commented on product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
> +  def getAllLecturers(usernames: Option[String], only_active: Option[Boolean]): ServiceCall[NotUsed, Seq[Lecturer]]
```suggestion
  def getAllLecturers(usernames: Option[String], onlyActive: Option[Boolean]): ServiceCall[NotUsed, Seq[Lecturer]]
```
We are using camelCase

2020-11-26 10:21 UTC, david-buderus commented on product_code/user_service/api/src/main/scala/de/upb/cs/uc4/user/api/UserService.scala
> +  def getAllAdmins(usernames: Option[String], only_active: Option[Boolean]): ServiceCall[NotUsed, Seq[Admin]]
```suggestion
  def getAllAdmins(usernames: Option[String], onlyActive: Option[Boolean]): ServiceCall[NotUsed, Seq[Admin]]
```
We are using camelCase

2020-11-26 11:09 UTC, david-buderus approved these changes

2020-11-26 11:27 UTC, lrschaef approved these changes

2020-11-26 11:59 UTC, merged