Feature/operation service
upb-uc4/lagom-core pull request #446
Opened 2021-01-27 10:29 UTC by dhelmert

### Reason for this PR
- Multi user signing is a multi step process, requiring a workflow that allows approving operations at a later date.

### Changes in this PR
- Created the operation service, for handling operations. operations are wrappers, containing a transactions and information regarding who has approved, and still needs to approve in order for the transaction to be allowed to be executed

- [X] Test written
- [ ] Changelog updated

2021-01-27 11:45 UTC, lrschaef requested changes
Changelogs need to be updated (Group Service and Operation Service)

2021-01-27 11:45 UTC, lrschaef commented on product_code/group_service/CHANGELOG.md
> +# [v0.15.1](https://github.com/upb-uc4/University-Credits-4.0/compare/group-v0.15.1...group-v0.15.1) (2020-XX-XX)
```suggestion
# [v0.16.1](https://github.com/upb-uc4/University-Credits-4.0/compare/group-v0.16.1...group-v0.16.1) (2021-XX-XX)
```

2021-01-27 11:45 UTC, lrschaef commented on product_code/operation_service/impl/src/test/scala/de/upb/cs/uc4/operation/impl/OperationServiceSpec.scala
> +    "get an operation as initiator" in {
```suggestion
    "get an operation as its initiator" in {
```

2021-01-27 11:45 UTC, lrschaef commented on product_code/operation_service/impl/src/test/scala/de/upb/cs/uc4/operation/impl/OperationServiceSpec.scala
> +    "get an operation with OwnerMismatch" in {
```suggestion
    "fail with OwnerMismatch on trying to get an operation as an uninvolved user" in {
```

2021-01-27 11:45 UTC, lrschaef commented on product_code/operation_service/impl/src/test/scala/de/upb/cs/uc4/operation/impl/OperationServiceSpec.scala
> +    "get operations where the user initiated the operation" in {
```suggestion
    "get all operations a user initiated, as the initiator" in {
```

2021-01-27 11:45 UTC, lrschaef commented on product_code/operation_service/impl/src/test/scala/de/upb/cs/uc4/operation/impl/OperationServiceSpec.scala
> +    "get operations where the user asks for a state" in {
```suggestion
    "get all operations with a specific state" in {
```

2021-01-27 11:45 UTC, lrschaef commented on product_code/operation_service/impl/src/test/scala/de/upb/cs/uc4/operation/impl/OperationServiceSpec.scala
> +    "get operations where the user asks for his watchlist" in {
```suggestion
    "get all operations from a user's watchlist, as the user" in {
```

2021-01-28 10:01 UTC, jonas-thiele approved these changes
Looks good to me

2021-01-28 10:06 UTC, david-buderus commented on product_code/group_service/impl/src/main/resources/hyperledger_assets/connection_profile_kubernetes_local.yaml
> +#      verify: false
It is only used in local testing, so yeah it should stay

2021-01-28 10:16 UTC, ldklenner approved these changes

2021-01-28 10:55 UTC, lrschaef approved these changes

2021-01-28 12:03 UTC, merged